version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - "23450:23450"
    tty: true
    container_name: node_app
    networks:
      - app-net

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: hogehoge
      MYSQL_DATABASE: testdb
    volumes:
      - ./data/mysql:/var/lib/mysql
    container_name: mysql
    networks:
      - app-net

  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    container_name: redis
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
